name: Node.js CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [18.19.1] # Use Node.js 18.19.1 to match the server

    steps:
      # 1. نسخ مجلد public الحالي على السيرفر إلى مكان مؤقت قبل النشر
      - name: Backup Public Folder from Server
        run: |
          mkdir -p /var/www/sunflower/_work/public-backup
          if [ -d "/var/www/sunflower/_work/sunflower/sunflower/server/public" ]; then cp -r /var/www/sunflower/_work/sunflower/sunflower/server/public /var/www/sunflower/_work/public-backup/; fi

      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Check Node.js version
        run: node -v

      - name: Install Client Dependencies
        working-directory: ./user
        run: |
          NODE_OPTIONS=--max-old-space-size=4096 npm install
          NODE_OPTIONS=--max-old-space-size=4096 npm run build

      - name: Install Admin Dependencies
        working-directory: ./admin
        run: |
          NODE_OPTIONS=--max-old-space-size=4096 npm install
          NODE_OPTIONS=--max-old-space-size=4096 npm run build

      - name: Install Server Dependencies
        working-directory: ./server
        run: |
          npm install

      # 2. استعادة مجلد public من النسخة الاحتياطية بعد التحديث
      - name: Restore Public Folder on Server
        run: |
          if [ -d "/var/www/sunflower/_work/public-backup/public" ]; then cp -r /var/www/sunflower/_work/public-backup/public /var/www/sunflower/_work/sunflower/sunflower/server/; fi

      # 3. إعادة تشغيل السيرفر
      - name: Restarting Server
        working-directory: ./server
        run: |
          pm2 stop 0
          pm2 start 0
          pm2 save
          sudo service nginx restart
