name: Node.js CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [18.19.1] # Use Node.js 18.19.1 to match the server

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Check Node.js version
        run: node -v

      - name: Install Client Dependencies
        working-directory: ./user
        run: |
          NODE_OPTIONS=--max-old-space-size=4096 npm install
          NODE_OPTIONS=--max-old-space-size=4096 npm run build

      - name: Install Client Dependencies
        working-directory: ./admin
        run: |
          NODE_OPTIONS=--max-old-space-size=4096 npm install
          NODE_OPTIONS=--max-old-space-size=4096 npm run build

      - name: Install Server Dependencies
        working-directory: ./server
        run: |
          NODE_OPTIONS=--max-old-space-size=4096 npm install

      - name: Deploy Application
        run: |
          # Deploy the server app while excluding public
          rsync -avz --exclude='public/' --exclude='.git/' ./server/ root@62.72.12.52:/var/www/sunflower/_work/sunflower/sunflower/server/

      - name: Restarting Server
        working-directory: ./server
        run: |
          pm2 stop 0
          pm2 start 0
          pm2 save
          sudo service nginx restart
